apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "democrm-v4.fullname" . }}
  labels:
    {{- include "democrm-v4.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "democrm-v4.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "democrm-v4.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "democrm-v4.fullname" . }}-conf
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                      name: {{ .Values.generatedDbUriSecret.name }}
                      key:  {{ .Values.generatedDbUriSecret.key }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
