apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Values.mongodbCommunity.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  type: ReplicaSet
  members: {{ .Values.mongodbCommunity.members }}
  version: {{ .Values.mongodbCommunity.version | quote }}
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: {{ .Values.mongodbCommunity.appUser.name }}
      db: admin
      passwordSecretRef:
        name: {{ include "democrm-v4.fullname" . }}-appuser-password
      roles:
        - name: readWrite
          db: {{ .Values.mongodbCommunity.appUser.db }}
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: {{ .Values.mongodbCommunity.storageSize }}
